git clone git://github.com/digitaltoad/vim-jade.git
git clone git://github.com/godlygeek/tabular.git
git clone git://github.com/nathanaelkane/vim-indent-guides.git
git clone git://github.com/ntpeters/vim-better-whitespace.git
git clone git://github.com/tpope/vim-fugitive.git
git clone git://github.com/tpope/vim-surround.git
git clone https://github.com/altercation/vim-colors-solarized.git
git clone https://github.com/easymotion/vim-easymotion.git
git clone https://github.com/fatih/vim-go.git
git clone https://github.com/groenewege/vim-less.git
git clone https://github.com/mbbill/undotree.git
git clone https://github.com/osyo-manga/vim-stripe.git
git clone https://github.com/scrooloose/nerdtree.git
git clone https://github.com/tpope/vim-pathogen.git
git clone https://github.com/vim-airline/vim-airline.git
git clone https://github.com/vim-syntastic/syntastic.git
git clone https://github.com/zeekay/vim-beautify.git
git clone https://github.com/scrooloose/nerdcommenter.git
